version: '3'

tasks:
  install:
    cmds:
      - go install -ldflags "-s -w"
      - ./scripts/install_shellhook.sh
    silent: true

  build:
    cmds:
      - go build -ldflags "-s -w" -o target/sevp
    silent: true

  scan:
    cmds:
      - gosec ./...
    silent: true

  unit-test:
    cmds:
      - go test -v ./...
    silent: true

  integration-test:
    cmds:
      - podman build -t sevp .
      - podman run --rm sevp

  lint:
    cmds:
      - golangci-lint run
    silent: true
