version: '3'

tasks:
  install:
    cmds:
      - go install -ldflags "-s -w"
      - ./scripts/install_shellhook.sh
    silent: true

  build:
    cmds:
      - go build -ldflags "-s -w" -o target/sevp
    silent: true

  scan:
    cmds:
      - gosec ./...
    silent: true
