#!/usr/bin/env bash

# to append to .zshrc
to_write=$(cat << EOF

############################################
# AUTOMATICALLY GENERATED BY SEVP
############################################

function _sevp() {
    if [[ -f ~/.sevp ]]; then
        eval \$(cat ~/.sevp)
    fi
}

precmd_functions+=(_sevp)

# DELETE UNTIL HERE TO UNINSTALL SEVP SHELLHOOK

EOF
)

if [ -f ~/.zshrc ]; then
    if grep -q "sevp" ~/.zshrc; then
        echo "sevp shellhook already in ~/.zshrc"
    else
        echo "$to_write" >> ~/.zshrc
        echo "Added shell hook to ~/.zshrc"
    fi
else
    echo "No ~/.zshrc found"
fi
